#!/usr/bin/env bash
# Should start apache and print an error if it fails to do so
sudo apt-get update
sudo apt-get install -y apache2
sudo /etc/init.d/apache2 start
echo "Hello Holberton" | sudo tee -a /var/www/html/index.html
sudo /etc/init.d/apache2 restart
